version: '3'
services: 
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: mquser
      RABBITMQ_DEFAULT_PASS: mqpassword
    ports: 
      - 5672:5672

  worker:
    build: .
    volumes:
      - .:/app
    command: celery -A event.celery worker --pidfile= --loglevel=DEBUG
