version: '3'
services: 
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: mquser
      RABBITMQ_DEFAULT_PASS: mqpassword
    ports: 
      - 5672:5672

  worker:
    build: .
    volumes:
      - .:/app
    command: celery -A event.celery worker --pidfile= --loglevel=DEBUG  # celery 5.x 버전부터는 명령어가 바뀌어서, 단어들의 순서가 기존이랑 다름.
    environment:
      BROKER_URL: "amqp://mquser:mqpassword@rabbitmq:5672//"  # worker는 같은 도커 컴포즈 네트워크 내에서 mq와 통신해야 하기 때문에, 서비스명을 적어줬음.